# Generated by Django 6.0.6 on 2026-06-19 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='shop_desciption',
            new_name='shop_description',
        ),
    ]
