# Generated by Django 6.0.6 on 2026-08-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='refund_method',
            field=models.CharField(blank=True, choices=[('wallet', 'BazaarX Wallet'), ('original', 'Original Payment Source'), ('cod_wallet', 'Wallet (COD Order)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
