# Generated by Django 6.0.6 on 2026-07-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_saveditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='abandoned_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
