# Generated by Django 6.0.6 on 2026-06-29 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('razorpay', 'Online Payment (Razorpay)'), ('cod', 'Cash on Delivery')], default='razorpay', max_length=20),
        ),
    ]
