# Generated by Django 6.0.6 on 2026-06-29 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Size, Color', max_length=100)),
                ('value', models.CharField(help_text='e.g. XL, Red', max_length=100)),
                ('stock', models.IntegerField(default=0)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to use the base product price', max_digits=10, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'ordering': ['name', 'value'],
            },
        ),
    ]
